name: dirctflutter
description: A Dart package for integrating Directus with Flutter applications.
version: 0.1.3
homepage: https://github.com/ra7bi/dirctflutter.git
repository: https://github.com/ra7bi/dirctflutter.git
issue_tracker: https://github.com/ra7bi/dirctflutter.git/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  http: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  lint: ^2.2.0
